mdmarks/urls.py
from django.urls import path
from .views import index, login, logout, school_profile, reset_password, students, instructions, admin_info
from .previews import StudentHMFormPreview, StudentALFormPreview
from .forms import StudentHMForm, StudentALForm

app_name = 'mdmarks'

urlpatterns = [
	path('', index, name='index'),
	path('login/', login, name='login'),
	path('logout/', logout, name='logout'),
	path('update-school-profile/', school_profile, name='profile'),
	path('reset-password/', reset_password, name='reset_password'),
	path('students/', students, name='students'),
	path('instructions/', instructions, name='instructions'),
	path('admin-info/', admin_info, name='admin_info'),
	path('student/hm/<slug:rollno>/', StudentHMFormPreview(StudentHMForm), name='student_hm'),
	path('student/al/<slug:rollno>/', StudentALFormPreview(StudentALForm), name='student_al'),
]

wbdata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from mdmarks.views import import_users

urlpatterns = [
    path('admin/auth/user/import/users/', import_users, name='import_users'),
    path('admin/', admin.site.urls),
    path('', include('mdmarks.urls', namespace='mdmarks')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admin-info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>WBBME INFO COUNT</title>
	<style type="text/css">
		h3{
			margin-bottom: 0;
		}
		p, ul{
			margin: 0
		}
	</style>
</head>
<body>
	<h3>No of HM Students (completed):</h3>
	<p>{{ complete_hm_students }}</p>

	<h3>No of AL Students (completed):</h3>
	<p>{{ complete_al_students }}</p>

	<h3>No. of Profiles Generated:</h3>
	<p>{{ no_of_profiles }}</p>

	<h3>No. of Schools with no data entry:</h3>
	<p>{{ incomplete_schools|length }}</p>

	<h3>List of Incomplete Schools</h3>
	<ul>
		{% for school in incomplete_schools %}
		<li>{{ school }} - {{ school.first_name }}</li>
		{% endfor %}
	</ul>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    {% block meta %}{% endblock %}
    <style>
    *{
        font-family: 'Roboto', sans-serif;
    }
    .errorlist {
        padding-left: 1rem;
        color: #6e0757;
        text-shadow: 0 0 black;
        list-style: none;
    }
    a.nav-link{
        font-weight: 400;
    }
    .base-section{
        position: absolute;   
        top: 0;
        min-height: 150vh;
        height: 100%;
        width: 100%;
        background: rgb(31,19,228);
        background: linear-gradient(214deg, rgba(31,19,228,1) 0%, rgba(50,50,215,1) 21%, rgba(50,153,215,1) 97%);
        /*z-index: -1;*/
    }  
    .btn-success{
        background-color: #16006e;
        border-color: #16006e;
    } 
    </style>
    {% block css %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top">
        <a href="{% url 'mdmarks:index' %}" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" height="50" alt="WBBME - Examination Marks Entry Portal">
            <span class="d-inline ml-2 my-auto" style="font-size:36px;color:#fff;letter-spacing: 1.2px;vertical-align:middle;">W.B.B.M.E.</span>
        </a>
        <button class=" navbar-toggler bg-light" data-toggle="collapse" data-target="#nav"><span class="navbar-toggler-icon"></span></button>
        <div class=" collapse navbar-collapse justify-content-between" id="nav">
            <ul class="navbar-nav ml-auto">
                <li class='nav-item'><a class='nav-link text-light text-uppercase px-3' href="{% url 'mdmarks:index' %}">Home</a></li>
                <li class='nav-item'><a class='nav-link text-light text-uppercase px-3' href="{% url 'mdmarks:students' %}">Students List</a></li>
                <li class='nav-item'><a class='nav-link text-light text-uppercase px-3' href="{% url 'mdmarks:instructions' %}">Instructions</a></li>
                {% if not request.user.is_authenticated %}<li class='nav-item'><a class='nav-link text-light text-uppercase px-3' href="{% url 'mdmarks:login' %}">Login</a></li>{% else %}<li class='nav-item'><a class='nav-link text-light text-uppercase px-3' href="{% url 'mdmarks:logout' %}">Logout</a></li>{% endif %}            
            </ul>
        </div>
    </nav>
    <section class="base-section">
        {% if messages %}{% for message in messages %}
        <div class="alert mb-0 alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-top: 76px;">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}{% endif %}
    </section>
    
    {% block content %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>